name: Deno CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  test:
    strategy:
      matrix:
        deno: ['v1.x']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno test --allow-run
        env:
          VR_SHELL: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
